### ISSUE TITLE
In manual mode, typeahead should accept `val` prop

### ISSUE THREAD

**Issue by david-davidson** [FormidableLabs/radon-typeahead#12]
We're using `radon-typeahead` in a scenario where we want to be able to clear the current search in response to an external action. We're also using it in manual mode, so we're simply passing down the `list` prop each render. I propose that, in manual mode, the typeahead also accept a `val` prop. It could look something like this:
```
getInitialState() {
  return {
    ...
    val: (this.props.manualMode && this.props.val) ? this.props.val : ""
  };
}
...
componentWillReceiveProps(nextProps) {
  ...
  if (nextProps.val && nextProps.manualMode) {
    this.setState({ val: nextProps.val });
  }
}
```
... that is, it would only affect users who 1.) opt in to manual mode and 2.) pass down `val`.

Are there any downsides to this I might be missing?

/cc @redfieldstefan

**Comment by rgerstenberger** [comment]
Looks reasonable to me. Triple check that it updates as expected.
